platzigram/urls.py
#Django modules
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#Local modules



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='post')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts Urls"""
#Dajango
from django.urls import path

#Views
from posts import views


urlpatterns = [
	path('', views.PostsFeedView.as_view(), name='feed'),
    path('posts/new/', views.CreatePostView.as_view(), name='create_posts'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
]

users/urls.py
"""USERS URLs"""

#Django
from django.urls import path


#Views
from users import views

urlpatterns = [
	path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('me/profile/', views.UpdateProfileView.as_view(), name='update_profile'),
	path('<str:username>/',views.UserDetailView.as_view(), name='detail'),
    
]

posts/models.py
"""Post models"""

#Django
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    """Post model."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modifie = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return Title and Username"""
        return '{} by @{} '.format(self.title, self.user.username)

users/models.py
"""Users models"""
#Django modules
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    """Profile model.
    Proxy model that extends the base data with other information.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.CharField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username"""
        return self.user.username

posts/forms.py
"""Post forms"""


#Django
from django import forms

#Local
from posts.models import Post

class PostForm(forms.ModelForm):
	"""The post form"""

	class Meta:
		"""Form settings"""

		model = Post
		fields = ('user','profile','title', 'photo')

users/forms.py
"""User Forms"""

#Django
from django import forms
from django.contrib.auth.models import User

from users.models import Profile


class SignupForm(forms.Form):
	"""Sign up Form."""

	username = forms.CharField(min_length=4, max_length=50)
	
	password = forms.CharField(max_length=70, widget=forms.PasswordInput())
	password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())

	first_name = forms.CharField(min_length=2, max_length=50)
	last_name = forms.CharField(min_length=2, max_length=50)

	email = forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput())

	def clean_username(self):
		"""Username must be unique"""
		username = self.cleaned_data['username']
		username_taken = User.objects.filter(username=username).exists()

		if username_taken:
			raise forms.ValidationError('Username is already in use.')
		return username

	def clean(self):
		"""Verify the password confirmation match"""

		data = super().clean()
		password = data['password']
		password_confirmation = data['password_confirmation']

		if password != password_confirmation:
			raise forms.ValidationError('Password do not match.')
		return data

	def save(self):
		"""Create same user"""
		data = self.cleaned_data
		data.pop('password_confirmation')

		user = User.objects.create_user(**data)
		profile = Profile(user=user)
		profile.save()

posts/views.py
"""Posts views module"""

#Djnago modules
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
#Utilities
from datetime import datetime
from posts.forms import PostForm
from posts.models import Post

class PostsFeedView(LoginRequiredMixin, ListView):
    """Return all publishe posts"""

    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'data'

class PostDetailView(LoginRequiredMixin, DetailView):
    """Detail of a post"""
    template_name = 'posts/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'

class CreatePostView(LoginRequiredMixin, CreateView):
    """Create new posts"""
    template_name = 'posts/new.html'
    form_class = PostForm
    seccess_url = reverse_lazy('feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile

        return context

users/views.py
"""User views"""
#Django
from django.urls import reverse
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, UpdateView

#Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile
#Forms
from users.forms import SignupForm
#Local modules


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view"""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'
    def get_context_data(self, **kwargs):
        """Add users post to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class LoginView(auth_views.LoginView):
    """Login VIew"""
    template_name = 'users/login.html'
    redirect_authenticated_user = True

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Log out from the platform"""
    template_name = 'users/login.html'

def signup_view(request):
    """sign up users"""
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = SignupForm()
    return render(
        request = request,
        template_name = 'users/signup.html',
        context = {'form': form}
        )

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update a profile"""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website','biography','phone_number','picture']

    def get_object(self):
        """Return User Profile"""
        return self.request.user.profile

    def get_success_url(self):
        """Return success url"""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username':username})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet"href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"crossorigin="anonymous">
    <link rel="stylesheet"href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}
    
    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top"id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5"style="border-right: 1px solid #efefef;"href="{% url 'post:feed' %}">
            <img src="{% static "img/instagram.png" %}"height="45"class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                        <img src="{{ request.user.profile.picture.url }}" class="rounded-circle"height="50" />
                        {% else %}
                        <img src="{% static 'img/default-profile.png' %}"height="35"class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{%url 'posts:create_posts' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/posts/detail.html
{% extends 'base.html' %}

{% block head_content %}
<title>Platzigram</title>
{% endblock %}
{% block container %}
	<div class="container">
		<div class="row">
			{% include 'posts/post_card.html' %}
		</div>
	</div>
{% endblock %}

templates/posts/feed.html
{% extends 'base.html' %} 
{% block head_content %}
<title>Platzigram feed</title>
{% endblock %}

{% block container %}
<div class="container">
    <div class="row">

         {% for post in data %}
            {% include 'posts/post_card.html' %}
         {% endfor %}
    </div>
</div>

{% endblock %}

templates/posts/new.html
{% extends 'base.html' %}

{% block head_content %}
<title>Create New Post</title>
{% endblock %}

{% block container %}
	<div class="container">
		<div class="row justify-content-md-center">
			<div class="col-6 pt-3 pb-3" id="profile-box">
				<h4 class="mb-4">Post a new photo!</h4>
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{% for error in form.errors %}
						<div class="alert alert-danger" role="alert">
							{% for e in error %}
							{{ e }}
							{% endfor %}
						</div>
					{% endfor %}
					<input type="hidden" name="user" value="{{ user.pk }}">
					<input type="hidden" name="profile" value="{{ profile.pk }}">

					{#Title field #}
					<div class="form-group">
						<input
							class="form-control {% if form.title.errors %} is-invalid{% endif %}"
							type="text"
							name="title"
							placeholder="Title"
							value="{% if forms.error %}{{ form.title.value }}{% else %}{{ profile.title }}{% endif %}"
							>
						<div class="invalid-feedback">
							{% for error in form.title.errors %}{{ error }}{% endfor %}
						</div>
					</div>
					
					{#Photo field #}
					<div class="form-group">
						<input
							class="form-control {% if form.photo.errors %} is-invalid{% endif %}"
							type="file"
							name="photo"
							placeholder="Photo"
							value="{% if forms.error %}{{ form.photo.value }}{% else %}{{ profile.photo }}{% endif %}"
							>
						<div class="invalid-feedback">
							{% for error in form.photo.errors %}{{ error }}{% endfor %}
						</div>
					</div>

					<button class="btn btn-primary btn-block mt-5">Publish!</button>			
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url 'users:detail' request.user.username %}">
        <img class="mr-3 rounded-circle" src="{{ post.profile.picture.url }}" height="35px" alt="{{ post.user.get_full_name }}"/>
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.username }}</p>
                {{ post.timestamp }}
        </div>
    </div>
        <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
        <p class="mt-1 ml-2">
        <a href="" style="color: #000; font-zise:20px;">
             <i class="fa fa-heart"></i>
        </a>30 likes
        </p>
        <p class="ml-2 mt-0 mb-2">
            <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
        </p>
</div>

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet"href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"crossorigin="anonymous" />
    <link rel="stylesheet"href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5"id="auth-container">
                <img src="{% static "img/instagram.png" %}"class="img-fluid rounded mx-auto d-block pb-4"style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ request.user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" height="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a href="{% url 'users:update_profile' %}" class="ml-5 btn btn-sm btn-outline-info">
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>
    <div class="container" id="user-posts">
       <div class="row mt-3">
           {% for post in posts %}
           <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
               <a class="border" href="">
                   <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid">
               </a>
           </div>
                
            {% endfor %}
       </div> 
    </div>
    
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}
        {% if forms.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Oh snap!</strong> Your username or password didn't match!
            </div>
        {% endif %}
        <fieldset class="form-group">
            <input type="text" name="username" class="form-control"  placeholder="Username">
        </fieldset>
        <fieldset class="form-group">
            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block mt-5">Sign in!</button>
        <p class="mt-4">Don't have and account yet? <a href="{% url 'users:signup' %}">Sign up here.</a></p>
    </form>
{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% block container %}
<form method="POST" action="{% url 'signup' %}">
	{% csrf_token %}
	{% if form.errors %}
		{% for error in form.errors %}
		<h6 class="alert alert-danger">{{ errors }}</h6>
		{% endfor %}
	{% endif %}
	<div class="form-group">
		<input class="form-control" type="text" placeholder="Username" name="username" required="true" />
	</div>

	<div class="form-group">
		<input class="form-control" type="password" placeholder="Password" name="password" required="true" />
	</div>
	
	<div class="form-group">
		<input class="form-control" type="password" placeholder="Password Confirmation" name="password_confirmation" required="true" />
	</div>
	
	<div class="form-group">
		<input class="form-control" type="text" placeholder="Firs Name" name="first_name" required="true" />
	</div>
	
	<div class="form-group">
		<input class="form-control" type="text" placeholder="Last Name" name="last_name" required="true" />
	</div>
	
	<div class="form-group">
		<input class="form-control" type="email" placeholder="email" name="email" required="true" />
	</div>
	<button type="submit" class="btn btn-primary btn-block mt-5">Register!</button>
</form>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }}</title>
{% endblock %}

{% block container %}

  <div class="container">

    <div class="row justify-content-md-center">
      <div class="col-6 p-4"id="profile-box">

        <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="media">
            {% if profile.picture %}
              <img src="{{ profile.picture.url }}" class="rounded-circle"height="50" />
            {% else %}
              <img src="{% static 'img/default-profile.png' %}" class="rounded-circle"height="50" />
            {% endif %}

            <div class="media-body">
              <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
              <p class="ml-4"><input type="file" name="picture" ></p>
            </div>
          </div>

          <hr><br>

          <div class="">
            <label>Website</label>
            <input
                class="form-control {% if form.website.errors %} is-invalid{% endif %}"
                name="website"
                type="text"
                placeholder="Website"
                value="{% if forms.erros %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                />
                <div class="invalid-feedback">
                  {% for error in form.website.errors %}
                  {{ error }}
                  {% endfor %}
                </div>
          </div>  

          <div class="">
            <label>Biography</label>
            <textarea 
                class="form-control {% if form.biography.errors %} is-invalid{% endif %}"
                name="biography">{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}
            </textarea>
              <div class="invalid-feedback">
                  {% for error in form.biography.errors %}
                  {{ error }}
                  {% endfor %}
              </div>
          </div>

          <div class="">
            <label>Phone number</label>
            <input
                class="form-control {% if form.phone_number.errors %} is-invalid{% endif %}"
                name="phone_number"
                type="text"
                placeholder="Phone number"
                value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                />
              <div class="invalid-feedback">
                  {% for error in form.phone_number.errors %}
                  {{ error }}
                  {% endfor %}
              </div>
          </div>

          <button class="btn btn-primary btn-block mt-5"type="submit">Update Info</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}